name: varanasi
description: A new Flutter project.
publish_to: "none"
version: 2.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  another_flushbar: ^1.10.28
  audio_service: ^0.18.3
  audio_session: ^0.1.6+1
  cached_network_image: ^3.1.0
  cloud_firestore: ^3.1.7
  convert: ^3.0.1
  cupertino_icons: ^1.0.2
  dart_des: ^1.0.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_cache: ^0.1.0
  flutter_downloader: ^1.7.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  jiosaavn_wrapper:
    # git: https://github.com/teamDrt280320/jiosaavn_wrapper
    path: ./packages/jiosaavn_wrapper
  just_audio: ^0.9.15
  just_audio_background: ^0.0.1-beta.1
  lint: ^1.7.2
  lottie: ^1.2.1
  marquee: ^2.2.0
  marquee_text: ^2.0.0
  palette_generator: ^0.3.1
  path_provider: ^2.0.6
  permission_handler: ^8.1.6
  persistent_bottom_nav_bar: ^4.0.2
  show_up_animation: ^2.0.0
  sliding_sheet: ^0.5.2

dev_dependencies:
  build_runner: ^2.1.4
  change_app_package_name: ^1.0.0
  flutter_gen_runner: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/lottie/"
    - "assets/logo/"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/launcher_icon.png"
